### ISSUE TITLE
Message description too lengthy

### ISSUE THREAD

**Issue by cuscada** [francisduvivier/aoc-discord-notifier-bot#10]
If the leaderboard is occupied with plenty of people, the message description seems to exceed 2048 chars and thus will cause a problem with the Discord API. An example to test is with Repl.it's private lb: `374141-a103628b`

This will pop up:
```
(node:21410) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
content: Must be 2000 or fewer in length.
embeds[0].description: Must be 2048 or fewer in length.
    at item.request.gen.end (/home/user/aoc/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
    at then (/home/user/aoc/node_modules/snekfetch/src/index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:21410) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:21410) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by cuscada** [comment]
Still, the same suggestion: Can I easily modify or turn off the detailed timestamps feature? Imho this is more unpleasant to look than your previous version.

![Screenshot 2020-12-12 210400](https://user-images.githubusercontent.com/18105757/101985961-928afd80-3cbd-11eb-827a-33ee8e9bb44e.jpg)

versus the _nicer_ previous one:
![Screenshot 2020-12-12 210502](https://user-images.githubusercontent.com/18105757/101985982-b64e4380-3cbd-11eb-931b-33e1b48106db.jpg)

**Comment by francisduvivier** [comment]
Hi, thanks for raising the issue. What you should know though is that only the changed timestamps since last leaderboard check will be shown, so the next time a star is added, it would not be shown anymore. 
For the case that this bot is running from the start and polling frequently, you would never see so many timestamps, except for the first time. 

I like the timestamps, but I agree the length should be limited.
Would you be ok with limiting them to at most the last 2 stars?

**Comment by cuscada** [comment]
Hi, thanks for replying. Yeah, I think it is good to limit them to at most the last 2 stars as you said.

Edit:
> .., you would never see so many timestamps, except for the first time.

Oh right, also we may consider limiting the leaderboard msg to let's say, top 100 people. That way the discord API won't probably have a problem for the first launch (initiation).

**Comment by francisduvivier** [comment]
Can't hurt indeed to limit the message, will add that

**Comment by francisduvivier** [comment]
Ok that merge should fix it. Let me know if that looks better to you!

**Comment by francisduvivier** [comment]
Ah and to answer the question:
> Can I easily modify or turn off the detailed timestamps feature?

If you would still like the timestamps turned off, you can comment out this line:
`lineElements.push(getNewStarTimesString(member, oldMember));` on [boardProcessor.js:59:5](https://github.com/francisduvivier/aoc-discord-notifier-bot/blob/4a5d0ad7d9f88dba3543711c58c22a5768ca1a4b/src/boardProcessor.js#L59)

**Comment by cuscada** [comment]
Awesome! I just investigated this issue further, and it seems that making `40` instead of `50` members is safer, since `50` (I tested it with Repl.it community's LB) still exceeding 2000 chars.

Anyway, kudos to you🙌

**Comment by francisduvivier** [comment]
> Awesome! I just investigated this issue further, and it seems that making `40` instead of `50` members is safer, since `50` (I tested it with Repl.it community's LB) still exceeding 2000 chars.
> 
> Anyway, kudos to you🙌

Thanks for that info!
Didn't look up that message limit, my bad, I'll just make sure the message is never longer than that.

**Comment by francisduvivier** [comment]
> > Awesome! I just investigated this issue further, and it seems that making `40` instead of `50` members is safer, since `50` (I tested it with Repl.it community's LB) still exceeding 2000 chars.
> > Anyway, kudos to you🙌
> 
> Thanks for that info!
> Didn't look up that message limit, my bad, I'll just make sure the message is never longer than that.

Well actually the message length per line and summary length is already limited, so if 40 works, that's a simpler solution. Just pushed that, thanks for experimenting and letting me know!

**Comment by cuscada** [comment]
No problem! I like this project, and happy to test it around.

Lowkey expecting new feature you had in mind to implement😀 (better before this xmas hahah)

> so if 40 works, that's a simpler solution.

A better "programmatically" solution is probably `splicing` up to first 2000 chars, then limit the last line below that cap. For example, 2000th char is at rank `45` (and it's interrupted, not full), so we cut it at line `44`. But that's a minor, and it's okay to not implement it if you think it's not worth the effort, no biggie.

**Comment by francisduvivier** [comment]
> > 
> 
> A better "programmatically" solution is probably `splicing` up to first 2000 chars, then li

Yeah I'm not sure about the calculation with the title and summary, getting the length of those into the calculation for the memberlines and then experimenting with discord feels like a pain. So I'll indeed leave it at 40 for now.

**Comment by francisduvivier** [comment]
Btw @grrlic, if you have other suggestions for features, let me know. For me myself the bot is fine right now but I'm certainly open to suggestions ;-).

**Comment by cuscada** [comment]
:D gladly.

**Comment by cuscada** [comment]
I have not really studied your code, but so far I observed that the timestamp updates only apply to the first line on the rank change. To be more clear, here is a perfect example;

![Screenshot 2020-12-12 232631](https://user-images.githubusercontent.com/18105757/101989281-de47a200-3cd1-11eb-9450-afb230c5995b.jpg)

The first one is quite straightforward, the user anonymous has its rank upgraded, hence only its timestamp is shown.
But for the second one, George and Arran's timestamps are not included. I am not sure if this is intended or not. Perhaps, if you are interested you may put additional information about the details of the leaderboard processing (rank changes, updates,e tc.) in the README.

Cheers.

**Comment by francisduvivier** [comment]
Good one! I left them out intentionally to only show changes, but indeed, better show it for everyone all the time. That will make it more uniform. Changing that right now. 
Not gonna put too much code details in the README, otherwise I'm gonna have to do double work every time I change something. But what I will do is put some flags at the top of the `boardProcessor.js`, which will make it easier to tweak stuff.

**Comment by francisduvivier** [comment]
@grrlic  I opened this issue for that: https://github.com/francisduvivier/aoc-discord-notifier-bot/issues/13
Implemented it in this [PR](https://github.com/francisduvivier/aoc-discord-notifier-bot/pull/12) Testing it a little now, will merge the PR soon. Some changes though
