### ISSUE TITLE
Improve Board processing tweakability

### ISSUE THREAD

**Issue by francisduvivier** [francisduvivier/aoc-discord-notifier-bot#13]

**Comment by cuscada** [comment]
Neat! But the null problem reappears now :")

```
(node:58252) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyNames (<anonymous>)
    at getAllStarTimes (/home/user/aoc2/src/boardProcessor.js:18:27)
    at getNewStarTimes (/home/user/aoc2/src/boardProcessor.js:11:32)
    at createMemberSummary (/home/user/aoc2/src/boardProcessor.js:113:24)
    at newMembers.map.member (/home/user/aoc2/src/boardProcessor.js:131:16)
    at Array.map (<anonymous>)
    at createSummary (/home/user/aoc2/src/boardProcessor.js:129:40)
    at postToDiscordIfChanged (/home/user/aoc2/src/bot.js:22:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:58252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:58252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Edit:
Tested safe until [commit](https://github.com/francisduvivier/aoc-discord-notifier-bot/commit/7c5f4e73945334530057a95661aeec530b06b10b)

**Comment by francisduvivier** [comment]
Thanks for testing, and I'm very sorry for that. I updated my test board data now, so shouldn't happen again.

**Comment by cuscada** [comment]
What a blaze fix! btw spoiler: learn about Chinese Remainder Theorem (crt) before doing the day 13 ;D

**Comment by francisduvivier** [comment]
Omg thanks a lot for that tip. I haven't been doing a lot of math last
years so these kinda advanced modular arithmetic assignments are always
quite a pain for me.
