### ISSUE TITLE
Bug in discordBot.ts

### ISSUE THREAD

**Issue by cuscada** [francisduvivier/aoc-discord-notifier-bot#2]
In line 28, the code `let members = membersObj && Object.getOwnPropertyNames(membersObj)?.map(key => membersObj[key]) || [];` has some problem in linter, and when executed `npm run start`, this happens:

```
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Module.m._compile (/home/runner/aoc-jslb/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/home/runner/aoc-jslb/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at main (/home/runner/aoc-jslb/node_modules/ts-node/src/bin.ts:198:14)
    at Object.<anonymous> (/home/runner/aoc-jslb/node_modules/ts-node/src/bin.ts:288:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oac-discord-notifier@1.0.0 start: `ts-node src/discordBot.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oac-discord-notifier@1.0.0 start script.
```

Playground: [https://repl.it/@grrlic/aoc-jslb#src/discordBot.ts](https://repl.it/@grrlic/aoc-jslb#src/discordBot.ts)

**Comment by francisduvivier** [comment]
Interesting, I'll check it out

**Comment by francisduvivier** [comment]
Ok this is because it's node v12 there and that does not support optional chaining yet, but I don't really need it now, so I'll make it compatible.

**Comment by francisduvivier** [comment]
Should be fixed now by changing the target in the tsconfig with this commit: https://github.com/francisduvivier/aoc-discord-notifier-bot/commit/c84537f1c20c4862befc0e10a7a5b2e7e31ae569.
Let me know if that works for you as well now ;-)

**Comment by cuscada** [comment]
Cool. That works now. Can't wait to see the new features you bring =D

**Comment by grrlic** [comment]
For the `leaderboardUrl` in the `config.json`, do you mean _https://adventofcode.com/2020/leaderboard/private/view/12345.json_ or without the .json suffix?

I've tried both, and it seems that with the `.json` one makes more sense, since the URL without the `.json`, will get a bad warning from Eric Wastl as if you are scraping the page. But anyway, I got this warning and not sure if the bot still works properly:

```
> oac-discord-notifier@1.0.0 start /home/runner/aoc-jslb
> ts-node src/discordBot.ts

Bot Started!
Checking leaderboard now
(node:157) UnhandledPromiseRejectionWarning: Error: Bad leaderboard response:404 Not Found

    at Object.<anonymous> (/home/runner/aoc-jslb/src/aocLeaderboard.ts:40:15)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/aoc-jslb/src/aocLeaderboard.ts:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:157) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:157) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Cheers,
grrlic
