### ISSUE TITLE
Bug with the latest release

### ISSUE THREAD

**Issue by cuscada** [francisduvivier/aoc-discord-notifier-bot#8]
Node version: `10.23.0`
p.s. Works fine (tested) until commit on 6 Dec, then encountered this error when pulling recently.

```
Requesting leaderboard from [https://adventofcode.com/2020/leaderboard/private/view/123456]
(node:19879) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of null
    at createMemberSummary (/home/user/aoc/src/boardProcessor.js:89:38)
    at newMembers.map.member (/home/user/aoc/src/boardProcessor.js:104:16)
    at Array.map (<anonymous>)
    at createSummary (/home/user/aoc/src/boardProcessor.js:102:40)
    at postToDiscordIfChanged (/home/user/aoc/src/bot.js:22:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:19879) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19879) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by francisduvivier** [comment]
Will check it out right now.

**Comment by francisduvivier** [comment]
Should be fixed with https://github.com/francisduvivier/aoc-discord-notifier-bot/pull/9, let me know if not

**Comment by cuscada** [comment]
Cool, it does fix the issue.

**Comment by cuscada** [comment]
One suggestion from me: The new change to the message full of timestamps is a bit annoying and the previous one is better IMHO.

**Comment by francisduvivier** [comment]
> One suggestion from me: The new change to the message full of timestamps is a bit annoying and the previous one is better IMHO.

Thanks for the feedback, will check how to improve it while still getting the interesting info that I want to see.
